const players = [
    {
        _id: '1',
        name: 'L. Messi',
        image: '/images/L. Messi.jpg',
        full_name: 'Lionel Andrés Messi Cuccittini',
        birth_date: '6/24/1987',
        age: 31,
        height_cm: 170.18,
        weight_kgs: 72.1,
        positions: 'CF,RW,ST',
        nationality: 'Argentina',
        overall_rating: 94,
        potential: 94,
        long_shots: 94,
        crossing: 86,
        finishing: 95,
        heading_accuracy: 70,
        short_passing: 92,
        volleys: 86,
        dribbling: 97,
        curve: 93,
        freekick_accuracy: 94,
        long_passing: 89,
        ball_control: 96,
        acceleration: 91,
        sprint_speed: 86,
        agility: 93,
        reactions: 95,
        balance: 95,
        shot_power: 85,
        jumping: 68,
        stamina: 72,
        strength: 66,
        aggression: 48,
        interceptions: 22,
        positioning: 94,
        vision: 94,
        penalties: 75,
        composure: 96,
        marking: 33,
        standing_tackle: 28,
        sliding_tackle: 26,
        work_rate: 'High/High',
        weak_foot: 4,
        skill_moves: 5,
        international_reputation: 5,
        best_position: 'RW',
        value_in_million: 110,
        release_clause_in_million: 250,
    },
    {
        _id: '2',
        name: 'C. Eriksen',
        image: '/images/C. Eriksen.jpg',
        full_name: 'Christian  Dannemann Eriksen',
        birth_date: '2/14/1992',
        age: 27,
        height_cm: 154.94,
        weight_kgs: 76.2,
        positions: 'CAM,RM,CM',
        nationality: 'Denmark',
        overall_rating: 88,
        potential: 89,
        long_shots: 89,
        crossing: 88,
        finishing: 81,
        heading_accuracy: 52,
        short_passing: 91,
        volleys: 80,
        dribbling: 84,
        curve: 86,
        freekick_accuracy: 87,
        long_passing: 89,
        ball_control: 91,
        acceleration: 76,
        sprint_speed: 73,
        agility: 80,
        reactions: 88,
        balance: 81,
        shot_power: 84,
        jumping: 50,
        stamina: 92,
        strength: 58,
        aggression: 46,
        interceptions: 56,
        positioning: 84,
        vision: 91,
        penalties: 67,
        composure: 88,
        marking: 59,
        standing_tackle: 57,
        sliding_tackle: 22,
        work_rate: 'Medium/Medium',
        weak_foot: 4,
        skill_moves: 4,
        international_reputation: 4,
        best_position: 'CAM',
        value_in_million: 55,
        release_clause_in_million: 100,
    },
    {
        _id: '3',
        name: 'P. Pogba',
        image: '/images/P. Pogba.jpg',
        full_name: 'Paul Pogba',
        birth_date: '3/15/1993',
        age: 25,
        height_cm: 190.5,
        weight_kgs: 83.9,
        positions: 'CM,CAM',
        nationality: 'France',
        overall_rating: 88,
        potential: 91,
        long_shots: 82,
        crossing: 80,
        finishing: 75,
        heading_accuracy: 75,
        short_passing: 86,
        volleys: 85,
        dribbling: 87,
        curve: 85,
        freekick_accuracy: 82,
        long_passing: 90,
        ball_control: 90,
        acceleration: 71,
        sprint_speed: 79,
        agility: 76,
        reactions: 82,
        balance: 66,
        shot_power: 90,
        jumping: 83,
        stamina: 88,
        strength: 87,
        aggression: 78,
        interceptions: 64,
        positioning: 82,
        vision: 88,
        penalties: 82,
        composure: 87,
        marking: 63,
        standing_tackle: 67,
        sliding_tackle: 67,
        work_rate: 'High/High',
        weak_foot: 4,
        skill_moves: 4,
        international_reputation: 5,
        best_position: 'CM',
        value_in_million: 80,
        release_clause_in_million: 150,
    },
    {
        _id: '4',
        name: 'L. Insigne',
        image: '/images/L. Insigne.jpg',
        full_name: 'Lorenzo Insigne',
        birth_date: '6/4/1991',
        age: 27,
        height_cm: 162.56,
        weight_kgs: 59.0,
        positions: 'LW,ST',
        nationality: 'Italy',
        overall_rating: 88,
        potential: 88,
        long_shots: 84,
        crossing: 86,
        finishing: 77,
        heading_accuracy: 56,
        short_passing: 85,
        volleys: 74,
        dribbling: 90,
        curve: 87,
        freekick_accuracy: 77,
        long_passing: 78,
        ball_control: 93,
        acceleration: 94,
        sprint_speed: 86,
        agility: 94,
        reactions: 83,
        balance: 93,
        shot_power: 75,
        jumping: 53,
        stamina: 75,
        strength: 44,
        aggression: 34,
        interceptions: 26,
        positioning: 83,
        vision: 87,
        penalties: 61,
        composure: 83,
        marking: 51,
        standing_tackle: 24,
        sliding_tackle: 22,
        work_rate: 'High/Medium',
        weak_foot: 4,
        skill_moves: 4,
        international_reputation: 4,
        best_position: 'LW',
        value_in_million: 60,
        release_clause_in_million: 120,
    },
    {
        _id: '5',
        name: 'K. Koulibaly',
        image: '/images/K. Koulibaly.jpg',
        full_name: 'Kalidou Koulibaly',
        birth_date: '6/20/1991',
        age: 27,
        height_cm: 187.96,
        weight_kgs: 88.9,
        positions: 'CB',
        nationality: 'Senegal',
        overall_rating: 88,
        potential: 91,
        long_shots: 15,
        crossing: 30,
        finishing: 22,
        heading_accuracy: 83,
        short_passing: 68,
        volleys: 14,
        dribbling: 69,
        curve: 28,
        freekick_accuracy: 28,
        long_passing: 60,
        ball_control: 63,
        acceleration: 70,
        sprint_speed: 75,
        agility: 50,
        reactions: 82,
        balance: 40,
        shot_power: 55,
        jumping: 81,
        stamina: 75,
        strength: 94,
        aggression: 87,
        interceptions: 88,
        positioning: 24,
        vision: 49,
        penalties: 33,
        composure: 80,
        marking: 91,
        standing_tackle: 88,
        sliding_tackle: 87,
        work_rate: 'High/High',
        weak_foot: 3,
        skill_moves: 2,
        international_reputation: 3,
        best_position: 'CB',
        value_in_million: 70,
        release_clause_in_million: 140,
    },
    {
        _id: '6',
        name: 'V. van Dijk',
        image: '/images/V. van Dijk.jpg',
        full_name: 'Virgil van Dijk',
        birth_date: '7/8/1991',
        age: 27,
        height_cm: 193.04,
        weight_kgs: 92.1,
        positions: 'CB',
        nationality: 'Netherlands',
        overall_rating: 88,
        potential: 90,
        long_shots: 64,
        crossing: 53,
        finishing: 52,
        heading_accuracy: 83,
        short_passing: 79,
        volleys: 45,
        dribbling: 70,
        curve: 60,
        freekick_accuracy: 70,
        long_passing: 81,
        ball_control: 76,
        acceleration: 74,
        sprint_speed: 77,
        agility: 61,
        reactions: 87,
        balance: 49,
        shot_power: 81,
        jumping: 88,
        stamina: 75,
        strength: 92,
        aggression: 82,
        interceptions: 88,
        positioning: 41,
        vision: 60,
        penalties: 62,
        composure: 87,
        marking: 90,
        standing_tackle: 89,
        sliding_tackle: 84,
        work_rate: 'High/High',
        weak_foot: 3,
        skill_moves: 2,
        international_reputation: 4,
        best_position: 'CB',
        value_in_million: 85,
        release_clause_in_million: 160,
    },
    {
        _id: '7',
        name: 'K. Mbappé',
        image: '/images/K. Mbappé.jpg',
        full_name: 'Kylian Mbappé',
        birth_date: '12/20/1998',
        age: 20,
        height_cm: 152.4,
        weight_kgs: 73.0,
        positions: 'RW,ST,RM',
        nationality: 'France',
        overall_rating: 88,
        potential: 95,
        long_shots: 78,
        crossing: 77,
        finishing: 88,
        heading_accuracy: 77,
        short_passing: 82,
        volleys: 78,
        dribbling: 90,
        curve: 77,
        freekick_accuracy: 63,
        long_passing: 73,
        ball_control: 91,
        acceleration: 97,
        sprint_speed: 96,
        agility: 93,
        reactions: 91,
        balance: 83,
        shot_power: 83,
        jumping: 79,
        stamina: 88,
        strength: 73,
        aggression: 65,
        interceptions: 37,
        positioning: 89,
        vision: 82,
        penalties: 73,
        composure: 85,
        marking: 32,
        standing_tackle: 32,
        sliding_tackle: 26,
        work_rate: 'High/Medium',
        weak_foot: 5,
        skill_moves: 5,
        international_reputation: 4,
        best_position: 'RW',
        value_in_million: 150,
        release_clause_in_million: 250,
    },
    {
        _id: '8',
        name: 'S. Agüero',
        image: '/images/S. Agüero.jpg',
        full_name: 'Sergio Leonel Agüero del Castillo',
        birth_date: '6/2/1988',
        age: 30,
        height_cm: 172.72,
        weight_kgs: 69.9,
        positions: 'ST',
        nationality: 'Argentina',
        overall_rating: 89,
        potential: 89,
        long_shots: 83,
        crossing: 70,
        finishing: 93,
        heading_accuracy: 77,
        short_passing: 81,
        volleys: 85,
        dribbling: 89,
        curve: 82,
        freekick_accuracy: 73,
        long_passing: 64,
        ball_control: 89,
        acceleration: 88,
        sprint_speed: 80,
        agility: 86,
        reactions: 90,
        balance: 91,
        shot_power: 88,
        jumping: 81,
        stamina: 76,
        strength: 73,
        aggression: 65,
        interceptions: 24,
        positioning: 92,
        vision: 83,
        penalties: 83,
        composure: 90,
        marking: 30,
        standing_tackle: 20,
        sliding_tackle: 12,
        work_rate: 'Medium/Medium',
        weak_foot: 3,
        skill_moves: 3,
        international_reputation: 3,
        best_position: 'Unknown',
        value_in_million: 120,
        release_clause_in_million: 250
    },
    {
        _id: '9',
        name: 'M. Neuer',
        image: '/images/M. Neuer.jpg',
        full_name: 'Manuel Neuer',
        birth_date: '3/27/1986',
        age: 32,
        height_cm: 193.04,
        weight_kgs: 92.1,
        positions: 'GK',
        nationality: 'Germany',
        overall_rating: 89,
        potential: 89,
        long_shots: 16,
        crossing: 15,
        finishing: 13,
        heading_accuracy: 25,
        short_passing: 55,
        volleys: 11,
        dribbling: 30,
        curve: 14,
        freekick_accuracy: 11,
        long_passing: 59,
        ball_control: 46,
        acceleration: 54,
        sprint_speed: 60,
        agility: 51,
        reactions: 84,
        balance: 35,
        shot_power: 25,
        jumping: 77,
        stamina: 43,
        strength: 80,
        aggression: 29,
        interceptions: 30,
        positioning: 12,
        vision: 70,
        penalties: 47,
        composure: 70,
        marking: 17,
        standing_tackle: 10,
        sliding_tackle: 11,
        work_rate: 'Medium/Medium',
        weak_foot: 3,
        skill_moves: 3,
        international_reputation: 3,
        best_position: 'Unknown',
        value_in_million: 75,
        release_clause_in_million: 150
    },
    {
        _id: '10',
        name: 'E. Cavani',
        image: '/images/E. Cavani.jpg',
        full_name: 'Edinson Roberto Cavani Gómez',
        birth_date: '2/14/1987',
        age: 32,
        height_cm: 185.42,
        weight_kgs: 77.1,
        positions: 'ST',
        nationality: 'Uruguay',
        overall_rating: 89,
        potential: 89,
        long_shots: 79,
        crossing: 70,
        finishing: 89,
        heading_accuracy: 89,
        short_passing: 78,
        volleys: 90,
        dribbling: 80,
        curve: 77,
        freekick_accuracy: 76,
        long_passing: 52,
        ball_control: 82,
        acceleration: 75,
        sprint_speed: 76,
        agility: 77,
        reactions: 91,
        balance: 59,
        shot_power: 87,
        jumping: 88,
        stamina: 92,
        strength: 78,
        aggression: 84,
        interceptions: 48,
        positioning: 93,
        vision: 77,
        penalties: 85,
        composure: 82,
        marking: 52,
        standing_tackle: 45,
        sliding_tackle: 39,
        work_rate: 'Medium/Medium',
        weak_foot: 3,
        skill_moves: 3,
        international_reputation: 3,
        best_position: 'Unknown',
        value_in_million: 60,
        release_clause_in_million: 120
    },
    {
        _id: '11',
        name: 'Sergio Busquets',
        image: '/images/Sergio Busquets.jpg',
        full_name: 'Sergio Busquets i Burgos',
        birth_date: '7/16/1988',
        age: 30,
        height_cm: 187.96,
        weight_kgs: 76.2,
        positions: 'CDM,CM',
        nationality: 'Spain',
        overall_rating: 89,
        potential: 89,
        long_shots: 54,
        crossing: 62,
        finishing: 67,
        heading_accuracy: 68,
        short_passing: 89,
        volleys: 44,
        dribbling: 80,
        curve: 66,
        freekick_accuracy: 68,
        long_passing: 82,
        ball_control: 88,
        acceleration: 50,
        sprint_speed: 52,
        agility: 66,
        reactions: 87,
        balance: 52,
        shot_power: 61,
        jumping: 66,
        stamina: 86,
        strength: 77,
        aggression: 85,
        interceptions: 87,
        positioning: 77,
        vision: 87,
        penalties: 60,
        composure: 93,
        marking: 90,
        standing_tackle: 86,
        sliding_tackle: 80,
        work_rate: 'Medium/Medium',
        weak_foot: 3,
        skill_moves: 3,
        international_reputation: 3,
        best_position: 'Unknown',
        value_in_million: 65,
        release_clause_in_million: 140
    },
    {
        _id: '12',
        name: 'T. Courtois',
        image: '/images/T. Courtois.jpg',
        full_name: 'Thibaut Courtois',
        birth_date: '5/11/1992',
        age: 26,
        height_cm: 198.12,
        weight_kgs: 96.2,
        positions: 'GK',
        nationality: 'Belgium',
        overall_rating: 89,
        potential: 90,
        long_shots: 17,
        crossing: 14,
        finishing: 14,
        heading_accuracy: 13,
        short_passing: 33,
        volleys: 12,
        dribbling: 13,
        curve: 19,
        freekick_accuracy: 20,
        long_passing: 35,
        ball_control: 23,
        acceleration: 46,
        sprint_speed: 52,
        agility: 61,
        reactions: 84,
        balance: 45,
        shot_power: 36,
        jumping: 68,
        stamina: 38,
        strength: 70,
        aggression: 23,
        interceptions: 15,
        positioning: 13,
        vision: 44,
        penalties: 27,
        composure: 66,
        marking: 20,
        standing_tackle: 18,
        sliding_tackle: 16,
        work_rate: 'Medium/Medium',
        weak_foot: 3,
        skill_moves: 3,
        international_reputation: 3,
        best_position: 'Unknown',
        value_in_million: 75,
        release_clause_in_million: 150
    },
    {
        _id: '13',
        name: 'M. ter Stegen',
        image: '/images/M. ter Stegen.jpg',
        full_name: 'Marc-André ter Stegen',
        birth_date: '4/30/1992',
        age: 26,
        height_cm: 187.96,
        weight_kgs: 84.8,
        positions: 'GK',
        nationality: 'Germany',
        overall_rating: 89,
        potential: 92,
        long_shots: 10,
        crossing: 18,
        finishing: 14,
        heading_accuracy: 11,
        short_passing: 42,
        volleys: 14,
        dribbling: 17,
        curve: 18,
        freekick_accuracy: 12,
        long_passing: 47,
        ball_control: 18,
        acceleration: 38,
        sprint_speed: 50,
        agility: 37,
        reactions: 86,
        balance: 43,
        shot_power: 22,
        jumping: 79,
        stamina: 35,
        strength: 78,
        aggression: 43,
        interceptions: 22,
        positioning: 11,
        vision: 70,
        penalties: 25,
        composure: 70,
        marking: 25,
        standing_tackle: 13,
        sliding_tackle: 10,
        work_rate: 'Medium/Medium',
        weak_foot: 3,
        skill_moves: 3,
        international_reputation: 3,
        best_position: 'Unknown',
        value_in_million: 80,
        release_clause_in_million: 160
    },
    {
        _id: '14',
        name: 'A. Griezmann',
        image: '/images/A. Griezmann.jpg',
        full_name: 'Antoine Griezmann',
        birth_date: '3/21/1991',
        age: 27,
        height_cm: 175.26,
        weight_kgs: 73.0,
        positions: 'CF,ST',
        nationality: 'France',
        overall_rating: 89,
        potential: 90,
        long_shots: 82,
        crossing: 82,
        finishing: 89,
        heading_accuracy: 84,
        short_passing: 84,
        volleys: 87,
        dribbling: 87,
        curve: 86,
        freekick_accuracy: 84,
        long_passing: 78,
        ball_control: 90,
        acceleration: 88,
        sprint_speed: 85,
        agility: 90,
        reactions: 90,
        balance: 82,
        shot_power: 82,
        jumping: 90,
        stamina: 86,
        strength: 62,
        aggression: 73,
        interceptions: 49,
        positioning: 91,
        vision: 85,
        penalties: 83,
        composure: 89,
        marking: 59,
        standing_tackle: 54,
        sliding_tackle: 48,
        work_rate: 'Medium/Medium',
        weak_foot: 3,
        skill_moves: 3,
        international_reputation: 3,
        best_position: 'Unknown',
        value_in_million: 100,
        release_clause_in_million: 180
    },
    {
        _id: '15',
        name: 'M. Salah',
        image: '/images/M. Salah.jpg',
        full_name: 'Mohamed Salah Ghaly',
        birth_date: '6/15/1992',
        age: 26,
        height_cm: 175.26,
        weight_kgs: 71.2,
        positions: 'RW,ST',
        nationality: 'Egypt',
        overall_rating: 89,
        potential: 90,
        long_shots: 83,
        crossing: 78,
        finishing: 90,
        heading_accuracy: 59,
        short_passing: 83,
        volleys: 76,
        dribbling: 89,
        curve: 83,
        freekick_accuracy: 60,
        long_passing: 74,
        ball_control: 88,
        acceleration: 94,
        sprint_speed: 91,
        agility: 91,
        reactions: 92,
        balance: 88,
        shot_power: 80,
        jumping: 68,
        stamina: 84,
        strength: 70,
        aggression: 63,
        interceptions: 55,
        positioning: 92,
        vision: 84,
        penalties: 75,
        composure: 91,
        marking: 38,
        standing_tackle: 43,
        sliding_tackle: 41,
        work_rate: 'Medium/Medium',
        weak_foot: 3,
        skill_moves: 3,
        international_reputation: 3,
        best_position: 'Unknown',
        value_in_million: 110,
        release_clause_in_million: 200
    },
    {
        _id: '16',
        name: 'P. Dybala',
        image: '/images/P. Dybala.jpg',
        full_name: 'Paulo Bruno Exequiel Dybala',
        birth_date: '11/15/1993',
        age: 25,
        height_cm: 152.4,
        weight_kgs: 74.8,
        positions: 'CAM,RW',
        nationality: 'Argentina',
        overall_rating: 89,
        potential: 94,
        long_shots: 88,
        crossing: 82,
        finishing: 84,
        heading_accuracy: 68,
        short_passing: 87,
        volleys: 88,
        dribbling: 92,
        curve: 88,
        freekick_accuracy: 88,
        long_passing: 75,
        ball_control: 92,
        acceleration: 87,
        sprint_speed: 83,
        agility: 91,
        reactions: 86,
        balance: 85,
        shot_power: 82,
        jumping: 75,
        stamina: 80,
        strength: 65,
        aggression: 48,
        interceptions: 32,
        positioning: 84,
        vision: 87,
        penalties: 86,
        composure: 84,
        marking: 23,
        standing_tackle: 20,
        sliding_tackle: 20,
        work_rate: 'Medium/Medium',
        weak_foot: 3,
        skill_moves: 3,
        international_reputation: 3,
        best_position: 'Unknown',
        value_in_million: 90,
        release_clause_in_million: 180
    },
    {
        _id: '17',
        name: 'L. Modrić',
        image: '/images/L. Modrić.jpg',
        full_name: 'Luka Modrić',
        birth_date: '9/9/1985',
        age: 33,
        height_cm: 172.0,
        weight_kgs: 66.0,
        positions: 'CM,CAM',
        nationality: 'Croatia',
        overall_rating: 91,
        potential: 91,
        long_shots: 84,
        crossing: 86,
        finishing: 76,
        heading_accuracy: 60,
        short_passing: 92,
        volleys: 75,
        dribbling: 91,
        curve: 85,
        freekick_accuracy: 80,
        long_passing: 93,
        ball_control: 92,
        acceleration: 72,
        sprint_speed: 66,
        agility: 89,
        reactions: 89,
        balance: 94,
        shot_power: 73,
        jumping: 55,
        stamina: 85,
        strength: 57,
        aggression: 61,
        interceptions: 72,
        positioning: 79,
        vision: 93,
        penalties: 74,
        composure: 91,
        marking: 58,
        standing_tackle: 70,
        sliding_tackle: 65,
        work_rate: 'High/High',
        weak_foot: 4,
        skill_moves: 4,
        international_reputation: 4,
        best_position: 'CM',
        value_in_million: 60,
        release_clause_in_million: 120
    },

    {
        _id: '18',
        name: 'Fernandinho',
        image: '/images/Fernandinho.jpg',
        full_name: 'Fernando Luiz Rosa',
        birth_date: '5/4/1985',
        age: 33,
        height_cm: 152.4,
        weight_kgs: 67.1,
        positions: 'CDM',
        nationality: 'Brazil',
        overall_rating: 87,
        potential: 87,
        long_shots: 78,
        crossing: 68,
        finishing: 69,
        heading_accuracy: 66,
        short_passing: 85,
        volleys: 74,
        dribbling: 77,
        curve: 70,
        freekick_accuracy: 72,
        long_passing: 83,
        ball_control: 82,
        acceleration: 68,
        sprint_speed: 67,
        agility: 72,
        reactions: 89,
        balance: 78,
        shot_power: 83,
        jumping: 78,
        stamina: 84,
        strength: 76,
        aggression: 87,
        interceptions: 89,
        positioning: 70,
        vision: 75,
        penalties: 61,
        composure: 79,
        marking: 87,
        standing_tackle: 86,
        sliding_tackle: 80,
        work_rate: 'Medium/Medium',
        weak_foot: 3,
        skill_moves: 3,
        international_reputation: 3,
        best_position: 'Unknown',
        value_in_million: 45,
        release_clause_in_million: 90
    },
    {
        _id: '19',
        name: 'G. Higuaín',
        image: '/images/G. Higuaín.jpg',
        full_name: 'Gonzalo Gerardo Higuaín',
        birth_date: '12/10/1987',
        age: 31,
        height_cm: 185.42,
        weight_kgs: 88.9,
        positions: 'ST',
        nationality: 'Argentina',
        overall_rating: 87,
        potential: 87,
        long_shots: 80,
        crossing: 68,
        finishing: 91,
        heading_accuracy: 79,
        short_passing: 74,
        volleys: 88,
        dribbling: 83,
        curve: 74,
        freekick_accuracy: 62,
        long_passing: 59,
        ball_control: 84,
        acceleration: 70,
        sprint_speed: 72,
        agility: 75,
        reactions: 86,
        balance: 69,
        shot_power: 86,
        jumping: 79,
        stamina: 70,
        strength: 85,
        aggression: 50,
        interceptions: 20,
        positioning: 92,
        vision: 74,
        penalties: 70,
        composure: 86,
        marking: 35,
        standing_tackle: 22,
        sliding_tackle: 18,
        work_rate: 'Medium/Medium',
        weak_foot: 3,
        skill_moves: 3,
        international_reputation: 3,
        best_position: 'Unknown',
        value_in_million: 50,
        release_clause_in_million: 100
    },
    {
        _id: '20',
        name: 'I. Rakitić',
        image: '/images/I. Rakitić.jpg',
        full_name: 'Ivan Rakitić',
        birth_date: '3/10/1988',
        age: 30,
        height_cm: 182.88,
        weight_kgs: 78.0,
        positions: 'CM,CDM',
        nationality: 'Croatia',
        overall_rating: 87,
        potential: 87,
        long_shots: 87,
        crossing: 84,
        finishing: 79,
        heading_accuracy: 59,
        short_passing: 87,
        volleys: 84,
        dribbling: 82,
        curve: 88,
        freekick_accuracy: 82,
        long_passing: 90,
        ball_control: 85,
        acceleration: 66,
        sprint_speed: 62,
        agility: 73,
        reactions: 80,
        balance: 66,
        shot_power: 84,
        jumping: 39,
        stamina: 83,
        strength: 71,
        aggression: 67,
        interceptions: 81,
        positioning: 80,
        vision: 86,
        penalties: 82,
        composure: 86,
        marking: 76,
        standing_tackle: 75,
        sliding_tackle: 73,
        work_rate: 'Medium/Medium',
        weak_foot: 3,
        skill_moves: 3,
        international_reputation: 3,
        best_position: 'Unknown',
        value_in_million: 60,
        release_clause_in_million: 120
    },



];

export default players;
